---

# This should _never_ be run on a production machine.
#   It installs packages which would be helpful to someone directly logged
#   in. Since the entire point of these deployments is to obviate that
#   need, the (possibly exploitable) tools this
#   installs and configures should be unnecessary.
- name: install some helpful packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ userland_packages }}"


