---
- name: install nginx
  yum:
    name: nginx
    state: present

# First, we check that there's only one string to modify, otherwise no
#   change is made and it fails safely. Also, the two strings must be
#   the same length, for obvious reasons. |nginx| = |ninja| = 5
- name: patch nginx binary
  shell: >
    ([ $(grep -a -o -e nginx$'\r' `which nginx` | wc -l) -eq 1 ]
    && sed -i 's/nginx\r/ninja\r/' `which nginx`) || true



